name: {{skill_name}}
description: {{description}}
version: 1.0.0
author: hyper

capabilities:
  - {{capability1}}
  - {{capability2}}

triggers:
  - command: "{{command}} <args>"

output:
  format: markdown
  save_to: ../research/{{skill_name}}/

requirements:
  - bash
  - curl
  # Add more as needed

notes: |
  Any additional notes about this skill...
